### ISSUE TITLE
Should error when no yaml file specified to lumen serve

### ISSUE THREAD

**Issue by jlstevens** [holoviz/lumen#115]
If you simply run `lumen serve` a blank page is served by Bokeh without any error indicating that the yaml file (typically `dashboard.yml`) needs to be specified.

**Comment by jbednar** [comment]
Also could consider looking for `dashboard.yml` by default (which would need to be addressed by the error message here if so).  ("No Lumen .yml file specified and the default of dashboard.yml not found"?)

**Comment by jlstevens** [comment]
That was the behavior I was (wrongly) assuming when I simply specified `lumen serve` with no extra arguments. Could print one line if defaulting to `dashboard.yml` ("No Lumen .yml specified, using dashboard.yml")

**Comment by philippjfr** [comment]
This should happen at the Bokeh level or at best the Panel level. Lumen is the worst place to do this since it doesn't actually subclass the serve command.
