### ISSUE TITLE
Incorrect URL for Precipitation Gallery

### ISSUE THREAD

**Issue by tlmille2** [holoviz/lumen#117]
On the demo gallery the precipitation demo launches to the incorrect URL - https://lumen.holoviz.org/gallery/precip.png

![image](https://user-images.githubusercontent.com/36211553/112869072-5cae3100-9082-11eb-9f49-9c06b5c95404.png)

Change 
https://lumen.holoviz.org/gallery/precip.png

to 

https://lumen.holoviz.org/gallery/precip.html

**Comment by philippjfr** [comment]
Thanks, fixed in https://github.com/holoviz/lumen/commit/8ad4cef6ba577eb17f3b7000305d210088f92d13
