### ISSUE TITLE
Spinner should stop when an error is encountered

### ISSUE THREAD

**Issue by jbednar** [holoviz/lumen#125]
I love the new automatic loading indicator on startup, but when there is an error in the .yml, it just spins away like:

![image](https://user-images.githubusercontent.com/1695496/114647119-2687c880-9ca2-11eb-8b5b-fdf43e5bb4bc.png)

Here I edited the `penguins` URL to make it point to a non-existent file, and got no feedback that there was an error until I checked my command-line terminal.  A spinner is useful to the extent that it accurately conveys the state of the app, which in this case is an error; can it switch to an error indicator (a red exclamation point?) if the app raises an exception? Or at least stop spinning?

**Comment by jbednar** [comment]
Plus that spinner is pretty dang big!

**Comment by philippjfr** [comment]
The spinner is sized relative to its container, but maybe we'll set a max-width in Panel.
