### ISSUE TITLE
Misleading error message for missing .yml file

### ISSUE THREAD

**Issue by jbednar** [holoviz/lumen#132]
![image](https://user-images.githubusercontent.com/1695496/114717084-506cd980-9cfa-11eb-81fd-38fdbd4afd2d.png)

**Comment by philippjfr** [comment]
Will be huge ordeal to improve that since it's many layers deep inside bokeh.

**Comment by jbednar** [comment]
Can we put in a test earlier to short circuit it, i.e. explicitly check if the .yml file exists?

**Comment by philippjfr** [comment]
I'd strongly favor making a suggestion for improving the bokeh error message. To my eyes it's relatively clear.

**Comment by jbednar** [comment]
My suggestion would be "File not found: C:\Users\Chris\dashboard.yaml". I have to infer from "Path" and "Bokeh server application" that it's saying that the file is not found; it isn't saying "file" and "Bokeh server application" sounds like it's about some internal browser machinery, not my Lumen app. Focusing on the actual specific problem, i.e. that it's trying to load a file and not finding it, seems like the way to communicate here.
