### ISSUE TITLE
lumen categorie in discourse

### ISSUE THREAD

**Issue by yougis** [holoviz/lumen#16]
hi, first, thanks for all your work guys!
I am verry exiting about Lumen and it´s potential.
I would try to work with but I need some help.

When do you open the new categorie in discourse?

My first attempt with Lumen was to create  a yalm specification for Dashbord but with no luck.  I may missed something about the yalm file cause "targets" wasnot parsed as expected in the __init__  method of Dashboard class. 

It will be helpfull if you give an exemple working file in the doc .

**Comment by philippjfr** [comment]
I'll be filling in the docs with a number of examples this week and can add a category in the coming days.

**Comment by yougis** [comment]
done , thanks
