### ISSUE TITLE
Native control UI element for enum/selector 

### ISSUE THREAD

**Issue by eli-pinkus** [holoviz/lumen#187]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### Describe the solution you'd like
a dropdown interface for a control related to a enumerated type field.

#### Describe alternatives you've considered
Using a string control and typing the desired var exactly (bad UI)

**Comment by jbednar** [comment]
Isn't that what happens already, i.e. won't you get a https://panel.holoviz.org/reference/widgets/Select.html in that case?

**Comment by eli-pinkus** [comment]
i was not able to get the widget to render on my test dashboard. will try again.

**Comment by eli-pinkus** [comment]
You're correct. my mistake.
