### ISSUE TITLE
Unable to launch penguin example: `__init__() got an unexpected keyword argument 'arg'`

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/lumen#286]
#### ALL software version info
https://gist.github.com/tomascsantos/593d449dd5d4c8a3094b730eef46fa26

#### Description of expected behavior and the observed behavior
Tried to follow getting started instructions, was unable to launch penguins example.

#### Complete, minimal, self-contained example code that reproduces the issue
<img width="624" alt="Screen Shot 2022-06-14 at 11 35 56 AM" src="https://user-images.githubusercontent.com/7690514/173558475-70f5a21b-5727-42c9-be32-4d76cc841ee1.png">

I copied `dashboard.yaml` from penguins directory in github. I'm probably doing something silly but not sure what it could be :/

**Comment by maximlt** [comment]
Hi @tomascsantos !

I intend this week to set up the gallery of Lumen so that the examples are actually deployed. I'll let you know if I also encounter that issue.
