### ISSUE TITLE
Make "This web page was generated from a Jupyter ..." more visible

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/lumen#316]
Right now the warning is hidden at the bottom of the web page and could easily be missed. 

https://pyviz-dev.github.io/lumen/user_guide/pipeline.html

![image](https://user-images.githubusercontent.com/19758978/188610655-65349013-8a3b-4e24-a37a-408fa789530e.png)

**Comment by philippjfr** [comment]
This issue should be moved to `nbsite`.

**Comment by maximlt** [comment]
There's a meta-issues on this here: https://github.com/holoviz/holoviz/issues/320
