### ISSUE TITLE
Host CSV dataset ourself

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/lumen#369]
Currently, the penguins' dataset (https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv) is used extensively in the new documentation. 

It should be added to this repo or an S3 (which we control).

**Comment by maximlt** [comment]
For hvPlot's docs I'd be happy if we could decide on some dataset that we use across HoloViz and host ourselves.

**Comment by jbednar** [comment]
I agree with hosting it ourselves, but don't think it's good to make every site use the same dataset; that would get pretty boring!

**Comment by philippjfr** [comment]
This was done for all Lumen examples.
