### ISSUE TITLE
StringView does not render HTML value, caused to the forgoten end quote  of HTML tag "style"

### ISSUE THREAD

**Issue by yougis** [holoviz/lumen#47]
in StringView, line  233
`params['object'] = f'<p style="font-size: {self.font_size}>{value}</p>'`

should be
`params['object'] = f'<p style="font-size: "{self.font_size}>{value}</p>'`

to be rendered properly in HTML page

**Comment by jbednar** [comment]
Not `params['object'] = f'<p style="font-size: {self.font_size}">{value}</p>'`?

**Comment by yougis** [comment]
yes , you right !

**Comment by jbednar** [comment]
Great. Care to make a PR?
