### ISSUE TITLE
Load  source from intake catalog give an error on python >= 3.7 : ValueError("Could not determine catalog to load.")

### ISSUE THREAD

**Issue by yougis** [holoviz/lumen#53]
this error is due to the intake.Catalog method which is deprecated for this use case.
here (intake.__init__) is the warning :
```
warnings.warn('deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog\n '
                          'If you want to open a generic URL, you should use intake.open_catalog')
```
I don't know why but we can't cast Catalog as list  :  
cats = list(self.cat)
return None

so we should use intake.open_catalog instead that create a YAMLFileCatalog that could be cast as list.

**Comment by philippjfr** [comment]
I don't think that check is really needed at all so I'm refactoring things a bit in #57.
