### ISSUE TITLE
LumenAI Wishlist

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#533]
- Data table readable by Agent
- JS ChatInterface buttons to download
- Suggestion buttons initially
- Outlier detection
- Rename Assistant to Captain/Leader/Crew
- Add intermediate steps to chat
- Theming making it look slicker

**Comment by ahuang11** [comment]
It's not released, but if you want to try it out, it's available here: https://github.com/holoviz/lumen/pull/519

**Comment by Coderambling** [comment]
Thanks for your quick response! What LLM is it based on?

**Comment by ahuang11** [comment]
[OpenAI or Llama-cpp-python models ](https://github.com/holoviz/lumen/pull/519/files#diff-dc864a2206353ab4b7498c9a9361f5c45af0c5fd84adbc59fe054515346e55d4R163)

**Comment by philippjfr** [comment]
Think most of this is done and anything else should be opened as distinct issues.
