### ISSUE TITLE
Lumen AI: Overflowing message container

### ISSUE THREAD

**Issue by droumis** [holoviz/lumen#592]
on chrome, lumen main (0.7.0a1), panel main (1.5.0a7), bokeh 3.5.0rc1

See green arrow:

![image](https://github.com/holoviz/lumen/assets/6613202/56aec4ce-dfb4-41cb-95f9-dff73ebd9991)

**Comment by ahuang11** [comment]
Partially closed in https://github.com/holoviz/panel/pull/6948

**Comment by droumis** [comment]
What is left to do?

**Comment by ahuang11** [comment]
Potentially closed in https://github.com/holoviz/panel/pull/7157
