### ISSUE TITLE
Lumen AI gets a bit laggy with too many tables/plots

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#600]
`Feed` also makes it bounce around upon re-loading.

**Comment by philippjfr** [comment]
There's definitely something wrong with `Feed`.

**Comment by philippjfr** [comment]
Quick flame graph:

<img width="1863" alt="Screenshot 2024-07-14 at 23 41 35" src="https://github.com/user-attachments/assets/0a6f9d5a-28a3-4955-b14f-3bf9f486f221">

There appear to be two separate causes for the slowness:

1. Deserializing model reference takes up A LOT of time.
2. Layout invalidation also is taking up a lot of time.

**Comment by philippjfr** [comment]
Think we've mostly resolved this now.
