### ISSUE TITLE
LumenAI should output plots/tables to the sidebar

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#606]
As to not crowd the chat.

**Comment by philippjfr** [comment]
Not sure I understand this one, plots/tables are the main output of the chat and when screen real estate is most important. Putting them in the sidebar seems to be the worst possible UI.

**Comment by ahuang11** [comment]
If you expand the sidebar width to 800-1000px, it can be something akin to the artifacts sidebar in Claude.

**Comment by philippjfr** [comment]
Think we have this now as part of the explorer UI.
