### ISSUE TITLE
date as widget filter : datetime fomat from schema  is not recognized properly

### ISSUE THREAD

**Issue by yougis** [holoviz/lumen#77]
When we use  filter widget with date as field, the format property in schema dict is 'datetime'.

This is not recognized under the _string_type method. The 2 format option is 'date" or 'date-time' but there is not 'datetime' as possible format option.

Then, the method does also not find  'inclusiveMinimum' and 'inclusiveMaximum' property to set the range.

**Comment by philippjfr** [comment]
Thanks @yougis! Will try to resolve that asap, unless you get a chance before I do.
