### ISSUE TITLE
Discuss Embeddings/Tools

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#804]
to be done...

**Comment by ahuang11** [comment]
- Coordinator
  - Agents
    - Tools

- Planner
  - ChatAgent
    - RelevantEmbeddingsTool
    - OnlineSearchTool
  - TableListAgent
  - SQLAgent


Query: Who owns this dataset?
1. Planner checks whether this info is available
2. If not, lists out all the agents and tools
3. Sees that ChatAgent can provide embeddings tool
4. Uses ChatAgent to run embeddings tool
5. Planner checks whether the query is resolved

Query: Use the A2 magical formula to plot a timeseries
1. Planner checks whether it knows whether it knows about the A2 magical formula
2. If not, lists out all the agents and tools
3. Sees that ChatAgent can provide online search tool
4. Tries searching online, but it has no reference to the A2 magical formula
5. Planner checks whether it has everything it needs
6. It realizes it still doesn't know the A2 magical formula
7. Remembers that it already used the online search tool, but sees that ChatAgent also provides embeddings tool
8. Uses that embeddings tool and finds relevant info about the A2 magical formula
9. Realizes it requires two columns, A1, and A2
10. Lists out table column and realizes has enough info
11. Uses SQLAgent to calculate from A1 and A2
12. Uses VegaLiteAgent to calculate timeseries


Query: Calculate the totally unreal formula result
1. Planner checks whether it knows whether it knows about the totally unreal formula result
2. If not, lists out all the agents and tools
3. Sees that ChatAgent can provide online search tool
4. Tries searching online, but it has no reference to thwe totally unreal formula
5. Planner checks whether it has everything it needs
6. It realizes it still doesn't know the totally unreal formula
7. Remembers that it already used the online search tool, but sees that ChatAgent also provides embeddings tool
8. Uses that embeddings tool and finds no relevant info
9. Planner exhausts all its agents/tools
10. Planner uses ChatAgent to say it does not have enough info to perform the operation and stops.

Thoughts:
1. Rename ChatAgent to DiscoveryAgent
2. maybe change/add to `check_validity` to `done_enough_research` or `has_enough_info`
3. What differentiates Agent from Tool? Agents provide output while tools provide context.
4. What context is provided to Tools? What kwargs does it accept? Just messages?
5. Add a Reviewer whose sole goal is to give a thumbs up or thumbs down

**Comment by philippjfr** [comment]
Thanks for writing this up. My general feeling is that some of what you suggested is too limiting and not quite general enough. What I'd like to ensure is that while we will ship a core set of Agents that are likely to be generally useful we should not give them special significance above others. So your suggestions that the `ChatAgent` is responsible for providing discovery or adding context elevates it above other agents. The other point I'd make is that we should clearly delineate the role of different actors and this also blurs that line quite a bit. So before I start I'd like to clearly define the role of different actors:

- `Actor` acts as the baseclass and describes any component that can be invoked when a user issues a prompt. Actors may modify the memory, respond to the user, generate output or merely add additional context.
- `Coordinator` is responsible for orchestrating multiple actors towards solving some goal. It can make plans, determine what additional context is needed and ensures that each actor has all the context it needs.
- `Agent` solves some sub-task in an effort to address the user query. It has certain dependencies that it `requires` and `provides` certain context for other agents to use. It may also request additional context through the use of context tools.

This is where we get to what is currently missing to fit embeddings and the ability to provide other context nicely into this framework. I will posit that there are two components missing from this ontology:

1. `ContextTool`: Given the user or agent prompt this kind of tool will provide additional context for other actors, e.g. look up context in a vector database, find the closest matching table names, run a Google search etc.
2. `FunctionTool`: Unlike the context tool which is used automatically by an actor to look up context this kind of tool can be explicitly invoked by an actor. It is more akin to what most cloud providers and libraries refer to as tools, e.g. to perform a calculation. This should work by extracting the function signature, having the LLM generate structured output to match the function signature and then invoking the function.

(As always the naming here is provisional)

Now the question I have is how much of this do we have to model out in our API right now and what can we punt until after a release. We currently have the problem that the embeddings (which are `ContextTool`s in my proposal) do not fit cleanly into the ontology of components we have, i.e. how do we cleanly allow our `SQLAgent` to use embeddings to find the most relevant table(s), how do we let the `ChatAgent` look up additional context using a RAG based approach to answer a user question using another embeddings database. So it does seem like we have to come up with an abstractions for that in the near term.

I'll play around with some approaches now and then write up my findings.

**Comment by philippjfr** [comment]
I will add that other libraries simply combine both tool types into one, i.e. a context tool is just another tool to be invoked by the LLM. That has the benefit that the LLM gets to decide when/if to invoke the tool, i.e. it only asks for additional context when needed but it also means that you have to make additional LLM calls to decide whether the tool invocation is needed.

**Comment by ahuang11** [comment]
I like the idea of both tool types into one, e.g.

- Tool baseclass
  - FunctionTool baseclass
    - MathTool
    - BigQueryTool
    - DuckDbTool
    - ContextTool baseclass
      - LocalEmbeddingsTool
      - GoogleSearchTool
    - ClosestTableTool
With that in mind, I'm wondering whether SQLAgent should be both generating and executing expressions, or whether it should only generate SQL expressions, and pushing the execution onto a tool?

I personally think we should implement tools prior to release. If not, we probably will have to do a 2.0 release.

For inspiration/reference
https://controlflow.ai/concepts/concepts

I really like the idea of completion agents
https://controlflow.ai/concepts/agents#assigning-completion-agents

And early termination conditions
https://controlflow.ai/patterns/running-tasks#early-termination-conditions

And multi-agent collab
https://controlflow.ai/patterns/running-tasks#multi-agent-collaboration

I am starting to wondering whether it'd be possible/worth the effort to refactor Lumen on top of ControlFlow so that we don't have to reinvent the wheel and maintain our version of agents/tools. They have instructor built-in https://controlflow.ai/patterns/task-results, and ControlFlow's "planner" seems to be able to recurse https://controlflow.ai/patterns/running-tasks#managing-the-agentic-loop

ControlFlow <-> Lumen
Flow <-> Coordinator
Tasks <-> requires/provides
Agents <-> Agents

I am just unsure about how to map the Coordinator's requires/provides (perhaps imperative creation https://controlflow.ai/patterns/dependencies#imperative-creation) or something like `process_email` (https://controlflow.ai/quickstart#composing-tasks-into-a-flow), or if that's even necessary based on

**Comment by ahuang11** [comment]
Nevermind, it seems like ControlFlow requires a Prefect login which is unfortunate. I thought it was standalone.
![Image](https://github.com/user-attachments/assets/7b4f10db-5d7b-452c-865d-d554242b2c2f)
