### ISSUE TITLE
Stopping the LLM should not raise a long traceback

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#822]
If I cancel it, it should not raise an error
![Image](https://github.com/user-attachments/assets/1cfa2da1-c82a-4c90-aee8-311e5f4e3250)

I think probably will need to implement:
https://github.com/holoviz/panel/issues/6047

**Comment by philippjfr** [comment]
Partial fix in https://github.com/holoviz/lumen/pull/850

Please review that one to make sure I didn't do something silly.

**Comment by philippjfr** [comment]
I think it's a little too silent now, likely have to set the interface to raise exceptions.

**Comment by ahuang11** [comment]
Ideally, we can set a custom exception: https://github.com/holoviz/panel/issues/6047

I can work on that.
