### ISSUE TITLE
Use Griffe's public API

### ISSUE THREAD

**Issue by pawamoy** [holoviz/lumen#897]
You're importing from the internal API:

https://github.com/holoviz/lumen/blob/82df710106169b22b05b3c2ac5315d30ddd4317e/lumen/ai/translate.py#L17-L18

...exposing yourself to breakages.

Public equivalent:

```python
from griffe import DocstringSectionKind, Docstring 
```

**Comment by ahuang11** [comment]
Thank you for spotting that. Fixed in https://github.com/holoviz/lumen/pull/898

**Comment by pawamoy** [comment]
Nice, thanks for the quick fix!
